lang: de

website:
  title: "Virtuelle Akademie | KI in der Lehre"
  description: "Forschung und Ressourcen zu KI in der Hochschullehre"

  navbar:
    left:
      - research/index.qmd
      - text: Lehre
        menu:
          - text: Kurse
            href: teaching/index.qmd
          - text: Workshops
            href: workshops/index.qmd
      - posts/index.qmd
    right:
      - about/index.qmd

  sidebar:
    - id: research
      title: "Forschung"
      style: "docked"
      search: true
      background: light
      contents:
        - research/index.de.qmd
    - id: teaching
      title: "Lehre"
      style: "docked"
      search: true
      background: light
      contents:
        - teaching/index.de.qmd
        - teaching/bfh-weiterbildung/index.de.qmd
        - teaching/cas-hochschuldidaktik/index.de.qmd
    - id: workshops
      title: "Workshops"
      style: "docked"
      search: true
      background: light
      contents:
        - workshops/index.de.qmd
        - workshops/special-topics/index.de.qmd
        - workshops/bespoke/index.de.qmd
