project:
  type: website
  output-dir: docs

website:
  title: "virtuelleakademie"
  navbar:
    left:
      - text: "Teaching"
        href: teaching/
      - text: "Research"
        href: research/
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  sidebar:
    - title: "Teaching"
      href: teaching/
      contents:
        - teaching/index.qmd
        - text: "Courses"
          href: teaching/courses/
        - text: "Resources"
          href: teaching/resources/
        - text: "Philosophy"
          href: teaching/philosophy/
    - title: "Research"
      href: research/
      contents:
        - research/index.qmd
        - research/projects/
        - research/publications/
        - research/collaborations/

format:
  html:
    theme:
      light: [yeti, styles/theme-slate.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true
