project:
  type: website
  output-dir: docs
  preview:
    port: 8803
    browser: true

babelquarto:
  mainlanguage: 'en'
  languages: ['de']
  languagelinks: 'navbar'
  languagecodes:
    - name: en
      text: "EN"
    - name: de
      text: "DE"

lang: en
license: "CC BY-SA 4.0"

website:
  title: "Virtuelle Akademie | KI in der Lehre"
  description: "Forschung und Ressourcen zu KI in der Hochschullehre"

  site-url: https://virtuelleakademie.github.io/
  repo-url: https://github.com/virtuelleakademie/virtuelleakademie.github.io
  repo-actions: [edit, issue]

  favicon: /assets/va-logo.png
  open-graph: true
  reader-mode: false
  page-navigation: true
  back-to-top-navigation: true

  search:
    location: navbar
    type: overlay

  navbar:
    background: light
    left:
      - research/index.qmd
      - text: Teaching
        menu:
          - text: Courses
            href: teaching/index.qmd
          - text: Workshops
            href: workshops/index.qmd
      - posts/index.qmd

    right:
      - about/index.qmd

    tools:
      - icon: house-fill
        text: "Hauptseite virtuelleakademie.ch"
        href: https://virtuelleakademie.ch
        target: _blank
      - icon: lightbulb-fill
        text: Knowledge Base
        href: https://virtuelleakademie.ch/knowledge-base/
        target: _blank
      - icon: github
        href: https://github.com/virtuelleakademie
        target: _blank

  sidebar:
    - id: research
      title: "Research"
      style: "docked"
      search: true
      background: light
      contents:
        - research/index.qmd
    - id: teaching
      title: "Teaching"
      style: "docked"
      search: true
      background: light
      contents:
        - teaching/index.qmd
        - teaching/bfh-weiterbildung/index.qmd
        - teaching/cas-hochschuldidaktik/index.qmd
    - id: workshops
      title: "Workshops"
      style: "docked"
      search: true
      background: light
      contents:
        - workshops/index.qmd
        - workshops/special-topics/index.qmd
        - workshops/bespoke/index.qmd

page-footer:
  left: "© 2026 Virtuelle Akademie | [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
  right:
    - icon: github
      href: https://github.com/virtuelleakademie
      target: _blank
    - icon: inbox-fill
      href: mailto:virtuelle.akademie@bfh.ch
      target: _blank

format:
  html:
    theme:
      light:
        - simplex
        - styles/custom.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true
    linkcolor: "#9A4665"

execute:
  cache: true
  freeze: auto
  execute-dir: project

editor:
  render-on-save: true

comments:
  hypothesis:
    theme: clean

revealjs-plugins:
  - attribution

filters:
  - timer
  - custom-callout

custom-callout:
  active-processing:
    icon-symbol: "📝"
    collapse: false
    color: "#333333"
