lang: de

website:
  title: "Virtuelle Akademie | KI in der Lehre"
  description: "Forschung und Ressourcen zu KI in der Hochschullehre"

  sidebar:
    - id: research
      title: "Forschung"
      style: "docked"
      search: true
      background: light
      contents:
        - research/index.de.qmd
    - id: teaching
      title: "Lehre"
      style: "docked"
      search: true
      background: light
      contents:
        - section: "Kurse"
          contents:
            - teaching/index.de.qmd
            - teaching/bfh-weiterbildung/index.de.qmd
            - teaching/cas-hochschuldidaktik/index.de.qmd
        - section: "Workshops"
          contents:
            - workshops/index.de.qmd
            - workshops/special-topics/index.de.qmd
            - workshops/bespoke/index.de.qmd
