project:
  type: website
  output-dir: docs

website:
  title: "Virtuelle Akademie"
  favicon: /assets/va-logo.png
  open-graph: true
  back-to-top-navigation: true
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - text: "Teaching"
        href: teaching/
      - text: "Research"
        href: research/

    right:
      - text: "About"
        href: about/
      
    tools:
      - icon: lightbulb-fill
        text: Knowledge Base
        href: https://virtuelleakademie.ch/knowledge-base/
        target: _blank
      - icon: github
        href: https://github.com/virtuelleakademie
        target: _blank

  sidebar:
    - title: "Teaching"
      href: teaching/
      contents:
        - teaching/index.qmd
        - text: "Courses"
          href: teaching/courses/
        - text: "Resources"
          href: teaching/resources/
        - text: "Philosophy"
          href: teaching/philosophy/
    - title: "Research"
      href: research/
      contents:
        - research/index.qmd
        - text: "Projects"
          href: research/projects/
        - text: "Publications"
          href: research/publications/
        - text: "Collaborations"
          href: research/collaborations/

page-footer:
  left: "© 2025 Virtuelle Akademie"
  right:
    - icon: github
      href: https://github.com/virtuelleakademie
      target: _blank
    - icon: inbox-fill
      href: mailto:virtuelle.akademie@bfh.ch
      target: _blank

format:
  html:
    theme:
      # light: [yeti, styles/theme-slate.scss]
      light: [simplex, styles/theme-slate.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true

filters:
  - timer
  - custom-callout
