project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - teaching/**/*.qmd
    - research/**/*.qmd
    - teaching/**/*.ipynb
    - research/**/*.ipynb
    - about/**/*.qmd
    - posts/**/*.qmd

website:
  title: "Virtuelle Akademie"

  site-url: https://virtuelleakademie.github.io/
  repo-url: https://github.com/virtuelleakademie
  # repo-actions: [edit, issue]

  favicon: /assets/va-logo.png
  open-graph: true
  reader-mode: false
  page-navigation: true
  back-to-top-navigation: true

  search:
    location: navbar
    type: overlay

  navbar:
    left:
      - text: "Teaching"
        href: teaching/
      - text: "Research"
        href: research/

    right:
      - text: "About"
        href: about/
      
    tools:
      - icon: lightbulb-fill
        text: Knowledge Base
        href: https://virtuelleakademie.ch/knowledge-base/
        target: _blank
      - icon: github
        href: https://github.com/virtuelleakademie
        target: _blank

  sidebar:
    - title: "Teaching"
      href: teaching/
      contents:
        - teaching/index.qmd
        - text: "Courses"
          href: teaching/courses/
        - text: "Resources"
          href: teaching/resources/
        - text: "Philosophy"
          href: teaching/philosophy/
    - title: "Research"
      href: research/
      contents:
        - research/index.qmd
        - text: "Projects"
          href: research/projects/
        - text: "Publications"
          href: research/publications/
        - text: "Collaborations"
          href: research/collaborations/

page-footer:
  left: "© 2025 Virtuelle Akademie"
  right:
    - icon: github
      href: https://github.com/virtuelleakademie
      target: _blank
    - icon: inbox-fill
      href: mailto:virtuelle.akademie@bfh.ch
      target: _blank

format:
  html:
    theme:
      light: [simplex, styles/custom.scss]
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    anchor-sections: true
    smooth-scroll: true

execute:
  cache: true
  freeze: auto
  execute-dir: project

comments:
  hypothesis:
    theme: clean

revealjs-plugins:
  - attribution

filters:
  - timer
  - custom-callout
